name: Aliyun Signin

on:
  schedule:
   # 每天国际时间 00:05 运行一次, 中国时间 08:05
    - cron: '05 00 * * *'
  workflow_dispatch:
jobs:
  signin:
    name: Aliyun Signin
    runs-on: ubuntu-latest
    steps:
      - uses: ImYrS/aliyun-auto-signin@main
        with:
          REFRESH_TOKENS: ${{ secrets.REFRESH_TOKENS }}
          GP_TOKEN: ${{ secrets.GP_TOKEN}}
          PUSH_TYPES: 'pushplus'
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
